apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/YOUR_ORG/argocd-apps-repo
    targetRevision: main
    path: frontend
    helm:
      releaseName: frontend
      values: |
        image:
          repository: 044302809167.dkr.ecr.us-east-1.amazonaws.com/ticket-booking/frontend
          tag: latest
          pullPolicy: IfNotPresent
        
        replicaCount: 2
        
        service:
          type: LoadBalancer
          port: 80
        
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
