apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-alb-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/test-booking-application/tools.git
    targetRevision: main
    path: ingress/istio-alb
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
